In [4]:
import random 
import sys

def piedra_papel_tijera():
    
    x = 3
    while x > 0:
        pc = random.choice(["piedra", "pi", "tijera", "ti", "papel", "pa"])
        jugador = input("Elija una opción: ").lower()
    
        if jugador == "piedra" or jugador == "pi":
            if pc == "piedra" or pc == "pi":
                print("El ordenador elige piedra, Empate!")
                continue
            elif pc == "papel" or pc == "pa":
                print("El ordenador elige papel, pierdes")
                x -= 1
            elif pc == "tijera" or pc == "ti":
                print("El ordenador elije tijera, ganas")
                x -= 1
                
        elif jugador == "tijera" or jugador == "ti":
            if pc == "piedra" or pc == "pi":
                print("El ordenador elige piedra, pierdes")
                x -= 1
            elif pc == "papel" or pc == "pa":
                print("El ordenador elige papel, ganas")
                x -= 1
            elif pc == "tijera" or pc == "ti":
                print("El ordenador elije tijera, empate!")
                continue
                
        elif jugador == "papel" or jugador == "pa":
            if pc == "piedra" or pc == "pi":
                print("El ordenador elige piedra, ganas")
                x -= 1
            elif pc == "papel" or pc == "pa":
                print("El ordenador elige papel, empate")
                continue
            elif pc == "tijera" or pc == "ti":
                print("El ordenador elije tijera, pierdes")
                x -= 1
                
        else:
            print("Introduzca una opción valida")
            
                
                

       

In [5]:
from random import choice
import piedra_papel_tijera as ppt
import sys

def resultado():
    jug_score = 0
    pc_score = 0
    x = 3

    while x > 0:
        pc = ppt.pc
        jugador = ppt.jugador
    
        if jugador == "piedra" or jugador == "pi":
            if pc == "piedra" or pc == "pi":
                continue
            elif pc == "papel" or pc == "pa":
                x -= 1
                pc_score += 1
            elif pc == "tijera" or pc == "ti":
                x -= 1
                jug_score += 1
  
        elif jugador == "tijera" or jugador == "ti":
            if pc == "piedra" or pc == "pi":
                x -= 1
                pc_score += 1
            elif pc == "papel" or pc == "pa":
                x -= 1
                jug_score += 1
            elif pc == "tijera" or pc == "ti":
                continue
                
        elif jugador == "papel" or jugador == "pa":
            if pc == "piedra" or pc == "pi":
                x -= 1
                jug_score += 1
            elif pc == "papel" or pc == "pa":
                continue
            elif pc == "tijera" or pc == "ti":
                x -= 1
                pc_score += 1
                
        else:
            print("Introduzca una opción valida")
            

    if jug_score == 2:
        print("El jugador gana la partida")
    else:
        print("El ordenador gana la partida")
        
resultado()

ModuleNotFoundError: No module named 'piedra_papel_tijera'

In [6]:
print(sys.path)

['C:\\Users\\34620\\Desktop\\Bootamp Data Science SEP\\Ramp up\\02 - Python Programming', 'C:\\Users\\34620\\anaconda3\\python38.zip', 'C:\\Users\\34620\\anaconda3\\DLLs', 'C:\\Users\\34620\\anaconda3\\lib', 'C:\\Users\\34620\\anaconda3', '', 'C:\\Users\\34620\\anaconda3\\lib\\site-packages', 'C:\\Users\\34620\\anaconda3\\lib\\site-packages\\locket-0.2.1-py3.8.egg', 'C:\\Users\\34620\\anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\34620\\anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\34620\\anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\Users\\34620\\anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\34620\\.ipython']


In [1]:
x = []

for a in range(4):
    x.append(a ** 2)
    
print(x)

[0, 1, 4, 9]


In [10]:
players = [180, 172, 178, 185, 190, 195, 192, 200, 210, 190]

mean = sum(players) / len(players)
stdvar = (sum([(i - mean)**2 for i in players]) / len(players)) ** 0.5

low = mean - stdvar
high = mean + stdvar

count = len([i for i in players if low < i < high])
print(count)

6


In [5]:
import statistics

players = [180, 172, 178, 185, 190, 195, 192, 200, 210, 190]



std = statistics.stdev(players)
mean =  statistics.mean(players)

for players in range(int(mean-std), int(mean+std)):
    print(players)

178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199


In [16]:
import numpy as np

x = np.array ([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
 
print(x.ndim) # 2
 
print(x.size) # 9
 
print(x.shape) # (3, 3)

y = np.arange(2,8,2)
print(y)


2
9
(3, 3)
[2 4 6]


In [17]:
x = np.arange(1, 8, 3)
z = x.reshape(3, 1)
print(z[1][0])

4


In [21]:
d = np.arange(1, 10)
print(d[d < 4])
print(d[d < 5]) and (d%2 == 0)

[1 2 3]
[1 2 3 4]


In [23]:
x = np.array([11, 42, 8, 5, 18])
z = x[x>15]
print(z.size)
print(z)

2
[42 18]


In [25]:
x = np.arange(3, 9)
print(x)
z = x.reshape(2, 3)
print(z)
print(z[1][1])

[3 4 5 6 7 8]
[[3 4 5]
 [6 7 8]]
7


In [15]:
x = np.arange(2, 8, 2)
x = np.append(x, x.size)
x = np.sort(x)
print(x[1])

3


In [27]:
x = np.arange(1, 5)
x = x*2
print(x)
print(x[:3].sum())

[2 4 6 8]
12


In [28]:
data = np.array([150000, 125000, 320000, 540000, 200000, 120000, 160000, 230000, 280000, 290000, 300000, 500000, 420000, 100000, 150000, 280000])

mean = np.mean(data)
std = np.std(data)
low = mean-std
high = mean+std
count = 0

for i in data:
    if low < i < high:
        count += 1

result = (count / len(data))*100

print(result)

62.5


In [3]:
import pandas as pd

x = {
'a': [1, 2],
'b': [3, 4],
'c': [5, 6]
}
df = pd.DataFrame(x)

print(df)

   a  b  c
0  1  3  5
1  2  4  6


In [4]:
import pandas as pd
data = {
    'a': [1, 2, 3],
    'b': [5, 8, 4]
}
df = pd.DataFrame(data)
df['c'] = df['a']+df['b']
print(df.iloc[2]['c'])

7
